name: Development-PR-Actions

on:
  # Triggers the workflow on pull request events but only for the development branch
  pull_request:
    branches: [ development ]
  # Triggers the workflow on branch deletion for master and development branches
  delete:
    branches:
      - master
      - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # 1. Protect branches from deletion
  protect-branches:
    if: ${{ github.event_name == 'delete' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if master branch is being deleted
        if: github.event.ref == 'refs/heads/master'
        run: |
          echo "Deletion of the master branch is not allowed."
          exit 1
      - name: Check if development branch is being deleted
        if: github.event.ref == 'refs/heads/development'
        run: |
          echo "Deletion of the development branch is not allowed."
          exit 1

  # 2. Super-Linter: a code analysis tool used to flag programming errors,
  # bugs, stylistic errors and suspicious constructs
  super-lint:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Lint code base
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # The checkout step
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 3. British English spell check on Markdowns, Python sources files, etc
  spellcheck:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .spellcheck.yml
