name: Development-PR-Actions

on:
  # Triggers the workflow on pull request events but only for the development branch
  pull_request:
    branches: [ development ]
  # Triggers the workflow on branch deletion for master and development branches
  delete:
    branches:
      - master
      - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # 1. 
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }})
          if [[ ! "$BRANCH_NAME" =~ ^release-Y ]]; then
            echo "Branch name $BRANCH_NAME is not allowed to merge into master. Only branches with the prefix 'release-Y' are allowed."
            echo "Example `release-Y24-15.0.7` for the 7th release in sprint 15, year 2024."
            exit 1
          fi
      - name: Allow merge
        run: echo "Branch name $BRANCH_NAME is allowed to merge into master."

  # 2. Super-Linter: a code analysis tool used to flag programming errors,
  # bugs, stylistic errors and suspicious constructs
  super-lint:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Lint code base
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # The checkout step
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 3. British English spell check on Markdowns, Python sources files, etc
  spellcheck:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .spellcheck.yml
